### ISSUE TITLE
error running example in vignette

### ISSUE THREAD

**Issue by jmfa** [lorenzocapp/adapref#2]
Hi,

Thanks for the very interesting package.
I'm trying to test the package using the example provided in the vignette but I keep getting an error related with the INLA package:

```
> res<- BNPR_PS_ada(coaldat,lengthout=100,zeta1=zeta$zeta1,zeta2=zeta$zeta2)
Error in inla.check.control(control.inla, data) : 
  Name `lincomb.derived.only' in control-argument `control.inla', is void.
```
I didn't get any errors during installation and I think I have all dependencies installed.
Do you have any idea of what might be causing this error?

I've installed INLA using the following command:
```
devtools::install_github(repo = "https://github.com/hrue/r-inla", ref = "stable", subdir = "rinla", build = FALSE)
```

Thanks in advance,
J

**Comment by lorenzocapp** [comment]
Hi, 

Thanks for looking into our package. Sorry about the inconvenience and the late reply. 

Let me look more into it. I don't get this issue. I will get back to you soon.

Best,
Lorenzo

**Comment by lorenzocapp** [comment]
Sorry for the late reply. It should have been fixed with a push of a few weeks ago.
